// Key poses of the parkour animation layer. Each one is a clip in the "Parkour" layer's blend
// tree, weighted by an animator parameter named "Pose" + the enum name (e.g. "PoseVaultTuck").
// Generated by Tools > Movement > Build Parkour Poses; swap in authored clips in the blend tree.
public enum ParkourPose
{
    None,
    VaultPlant,
    VaultTuck,
    VaultLand,
    ClimbReach,
    ClimbHang,
    ClimbPull,
    ClimbMantle,
    Crouch,
    StepUp,
}
